CommentIcon
marussia1996/Vizitki pull request #11
Opened 2023-01-12 17:45 UTC by Ev-Kos

2023-01-12 18:15 UTC, forfrontskill requested changes

2023-01-12 18:15 UTC, forfrontskill commented on src/components/CommentIcon/CommentIcon.tsx
> +export const CommentIcon: FC = () => {
FC - не обязательно т.к. нет children.
Лучше сразу добавить все необходимые Props и типизацию

2023-01-12 18:15 UTC, forfrontskill commented on src/components/CommentIcon/CommentIcon.tsx
> +      {/* в зависимости от роута, стиля страницы, отправлен или нет коммент стиль должен меняться на countPink*/}
Лучше сразу добавить props, отвечающий за стилизацию

2023-01-12 18:15 UTC, forfrontskill approved these changes

2023-01-13 08:14 UTC, marussia1996 approved these changes

2023-01-13 08:35 UTC, merged