create InputDay
marussia1996/Vizitki pull request #18
Opened 2023-01-14 17:45 UTC by marussia1996

2023-01-15 08:16 UTC, TheVadiratti requested changes

2023-01-15 08:16 UTC, TheVadiratti commented on src/components/CustomInput/CustomInput.tsx
> +import React, {forwardRef} from "react";
оу, классный код))

2023-01-15 09:06 UTC, marussia1996 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Верстка компонента: InputDay](https://trello.com/c/AWsu2yFE/27-%D0%B2%D0%B5%D1%80%D1%81%D1%82%D0%BA%D0%B0-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0-inputday)

2023-01-16 16:46 UTC, Ev-Kos approved these changes

2023-01-17 06:16 UTC, TheVadiratti approved these changes

2023-01-17 08:07 UTC, merged