inputs refactoring
marussia1996/Vizitki pull request #31
Opened 2023-01-18 10:59 UTC by evgsamalex

move inputs to shared

2023-01-18 12:03 UTC, marussia1996 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Рефакторинг инпутов](https://trello.com/c/xLiqiDfr/52-%D1%80%D0%B5%D1%84%D0%B0%D0%BA%D1%82%D0%BE%D1%80%D0%B8%D0%BD%D0%B3-%D0%B8%D0%BD%D0%BF%D1%83%D1%82%D0%BE%D0%B2)

2023-01-18 13:09 UTC, marussia1996 requested changes
--- .react-datepicker__day--selected {
    color: #FFF !important; -- надо добавить !important
--- .react-datepicker__day:hover {
    background-color: #F8F8F8;
    color: #100C34 !important; -- надо добавить !important
Если не сложно сделай, это видимо я накосячила)

2023-01-18 13:09 UTC, marussia1996 commented on src/shared/inputs/Input/Input.module.scss
> +  padding: 12px 16px;
padding: 11 12; чтобы высота совпадала с макетом, и отступы там у них 12px по бокам

2023-01-18 13:09 UTC, marussia1996 commented on src/shared/inputs/Input/Input.module.scss
> +
input:focus-visible  надо сделать outline: none, а то chrome добавляет стиль

2023-01-18 13:09 UTC, marussia1996 commented on src/shared/inputs/InputFile/InputFile.module.scss
> +  margin-right: 8px;
все input-wrapper должны иметь отступ margin-right: 12px;

2023-01-18 13:09 UTC, marussia1996 commented on src/shared/inputs/InputFilter/InputFilter.module.scss
>    margin-right: 8px;
все input-wrapper должны иметь отступ margin-right: 12px;

2023-01-18 13:09 UTC, marussia1996 commented on src/shared/inputs/InputDay/InputDay.module.scss
> +  margin-right: 8px;
все input-wrapper должны иметь отступ margin-right: 12px;

2023-01-18 13:09 UTC, marussia1996 commented on src/shared/inputs/InputDay/InputDay.module.scss
> +  pointer-events: none;
pointer-events: none; тогда же отменится курсор, зачем?
color: $placeholder; предполагаю, что это свойство должно появляться, когда дата уже выбрана

2023-01-18 13:09 UTC, marussia1996 commented on src/shared/inputs/InputTextArea/InputTextArea.tsx
> +
textArea надо убрать возможность растягивания и установить максимальное количество строчек или  высоту

2023-01-18 16:07 UTC, evgsamalex commented on src/shared/inputs/InputDay/InputDay.module.scss
> +  pointer-events: none;
вроде не отменяется. это чтобы сквозь него можно было кликнуть. так как клик происходить по всему полю, иконка перекрывает

2023-01-18 16:18 UTC, marussia1996 commented on src/shared/inputs/InputDay/InputDay.module.scss
> +  pointer-events: none;
у меня сейчас нет курсора при наведении, есть только input-у основному назначить курсор или убрать это свойство, то будет курсор, мб на инпут навесить, а здесь с обертки убрать?

2023-01-18 18:40 UTC, forfrontskill commented on src/shared/inputs/Input/Input.module.scss
> +
Нужно во всех импутах так сделать....

2023-01-18 18:42 UTC, forfrontskill submitted a review, later dismissed

2023-01-18 18:45 UTC, forfrontskill commented
Пробежался, все хорошо. @marussia1996 отлично посмотрела

2023-01-19 06:39 UTC, evgsamalex commented on src/shared/inputs/Input/Input.module.scss
> +  padding: 12px 16px;
по 12 со всех сторон

2023-01-19 07:03 UTC, evgsamalex commented
все поправил можно мержить

2023-01-19 07:11 UTC, marussia1996 approved these changes

2023-01-19 07:13 UTC, merged